version: "3.7"
services:
  minio:
    image: minio/minio:latest
    hostname: minio
    container_name: minio
    restart: always
    volumes:
      - ./infrastracture_data/minio/data/:/data
    env_file:
      - .env
    ports:
      - "${MINIO_PORT}:9001"
    environment:
      MINIO_ROOT_USER: ${AWS_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${AWS_SECRET_ACCESS_KEY}
    command: ["server",  "--console-address", ":9001" , "/data/"]


  createbuckets:
    image: minio/mc
    env_file:
      - .env
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 ${AWS_ACCESS_KEY_ID} ${AWS_SECRET_ACCESS_KEY};
      /usr/bin/mc mb myminio/${MINIO_BUCKET};
      /usr/bin/mc policy set public myminio/${MINIO_BUCKET};
      exit 0;
      "
