FROM python:3.10

# Install python packages
RUN pip install --upgrade pip
RUN pip install mlflow==1.19.0 boto3==1.20.20 psycopg2==2.9.3 protobuf==3.20.0 numpy==1.23.4 SQLAlchemy==1.4.35

run echo $MLFLOW_S3_ENDPOINT_URL